=== Exymat/haproxy-vscode/syntaxes/tmlanguage.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "TextMate Grammar",
  "type": "object",
  "required": [
    "name",
    "scopeName",
    "patterns",
    "repository"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "scopeName": {
      "type": "string"
    },
    "fileTypes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "firstLineMatch": {
      "type": "string"
    },
    "foldingStartMarker": {
      "type": "string"
    },
    "foldingStopMarker": {
      "type": "string"
    },
    "patterns": {
      "$ref": "#/$defs/patternList"
    },
    "repository": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/ruleContainer"
      }
    },
    "injections": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/ruleContainer"
      }
    }
  },
  "additionalProperties": true,
  "$defs": {
    "patternList": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/pattern"
      }
    },
    "captures": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "$ref": "#/$defs/capture"
        }
      },
      "additionalProperties": false
    },
    "capture": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "patterns": {
          "$ref": "#/$defs/patternList"
        }
      },
      "additionalProperties": true
    },
    "ruleContainer": {
      "type": "object",
      "properties": {
        "patterns": {
          "$ref": "#/$defs/patternList"
        }
      },
      "additionalProperties": true
    },
    "pattern": {
      "type": "object",
      "properties": {
        "include": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "contentName": {
          "type": "string"
        },
        "match": {
          "type": "string"
        },
        "begin": {
          "type": "string"
        },
        "end": {
          "type": "string"
        },
        "captures": {
          "$ref": "#/$defs/captures"
        },
        "beginCaptures": {
          "$ref": "#/$defs/captures"
        },
        "endCaptures": {
          "$ref": "#/$defs/captures"
        },
        "patterns": {
          "$ref": "#/$defs/patternList"
        },
        "applyEndPatternLast": {
          "type": "integer"
        }
      },
      "additionalProperties": true
    }
  }
}

=== Exymat/haproxy-vscode/syntaxes/haproxy-2.6.tmLanguage.json
{
  "$schema": "./tmlanguage.schema.json",
  "name": "HAProxy 2.6",
  "scopeName": "source.haproxy",
  "patterns": [
    {
      "include": "#comments"
    },
    {
      "include": "#preprocessor-directives"
    },
    {
      "include": "#strings"
    },
    {
      "include": "#sections"
    },
    {
      "include": "#directives-with-values"
    },
    {
      "include": "#directives-multiword"
    },
    {
      "include": "#cache-keywords"
    },
    {
      "include": "#schema-directives"
    },
    {
      "include": "#sample-fetches"
    },
    {
      "include": "#sample-function-calls"
    },
    {
      "include": "#acl-expressions"
    },
    {
      "include": "#sample-expressions"
    },
    {
      "include": "#rule-actions"
    },
    {
      "include": "#check-actions"
    },
    {
      "include": "#log-format-prefixes"
    },
    {
      "include": "#log-line"
    },
    {
      "include": "#bind-param-pairs"
    },
    {
      "include": "#single-arg-directives"
    },
    {
      "include": "#redirect-keywords"
    },
    {
      "include": "#addresses"
    },
    {
      "include": "#http-methods"
    },
    {
      "include": "#versions"
    },
    {
      "include": "#sample-fetches"
    },
    {
      "include": "#numbers"
    },
    {
      "include": "#acl-flags"
    },
    {
      "include": "#comparison-operators"
    },
    {
      "include": "#condition-keywords"
    },
    {
      "include": "#boolean-literals"
    },
    {
      "include": "#enums"
    },
    {
      "include": "#modifiers"
    },
    {
      "include": "#expressions"
    },
    {
      "include": "#filenames"
    },
    {
      "include": "#punctuation"
    },
    {
      "include": "#identifiers"
    }
  ],
  "repository": {
    "comments": {
      "patterns": [
        {
          "name": "comment.line.number-sign.haproxy",
          "match": "#.*$"
        }
      ]
    },
    "preprocessor-directives": {
      "patterns": [
        {
          "name": "keyword.control.preprocessor.haproxy",
          "match": "^\\s*\\.(?:if|elif|else|endif|diag|notice|warning|alert)\\b"
        }
      ]
    },
    "strings": {
      "patterns": [
        {
          "name": "string.quoted.double.haproxy",
          "begin": "\"",
          "end": "(\"|$)",
          "patterns": [
            {
              "include": "#log-format-content"
            },
            {
              "name": "constant.character.escape.haproxy",
              "match": "\\\\."
            }
          ]
        },
        {
          "name": "string.quoted.single.haproxy",
          "begin": "'",
          "end": "('|$)",
          "patterns": [
            {
              "include": "#log-format-content"
            },
            {
              "name": "constant.character.escape.haproxy",
              "match": "\\\\."
            }
          ]
        }
      ]
    },
    "sections": {
      "patterns": [
        {
          "match": "(?m)^(?:\\t| )*(defaults)\\s+(\\S+)(?:\\s+(from)\\s+(\\S+))?",
          "captures": {
            "1": {
              "name": "entity.name.type.section.haproxy"
            },
            "2": {
              "name": "entity.name.type.class.proxy.haproxy"
            },
            "3": {
              "name": "keyword.other.directive.haproxy"
            },
            "4": {
              "name": "entity.name.type.proxy.haproxy"
            }
          }
        },
        {
          "match": "(?m)^(?:\\t| )*((?:frontend|backend|listen))\\s+(\\S+)(?:\\s+(from)\\s+(\\S+))?",
          "captures": {
            "1": {
              "name": "entity.name.type.section.haproxy"
            },
            "2": {
              "name": "entity.name.type.class.proxy.haproxy"
            },
            "3": {
              "name": "keyword.other.directive.haproxy"
            },
            "4": {
              "name": "entity.name.type.proxy.haproxy"
            }
          }
        },
        {
          "match": "(?m)^(?:\\t| )*((?:http\\-errors|log\\-forward|resolvers|crt\\-list|fcgi\\-app|userlist|mailers|program|cache|peers|ring))\\s+(\\S+)",
          "captures": {
            "1": {
              "name": "entity.name.type.section.haproxy"
            },
            "2": {
              "name": "entity.name.type.class.proxy.haproxy"
            }
          }
        },
        {
          "name": "entity.name.type.section.haproxy",
          "match": "(?m)^(?:\\t| )*((?:http\\-errors|log\\-forward|resolvers|crt\\-list|defaults|fcgi\\-app|frontend|userlist|backend|mailers|program|global|listen|cache|peers|ring))\\b"
        }
      ]
    },
    "cache-keywords": {
      "patterns": [
        {
          "name": "keyword.other.directive.haproxy",
          "match": "\\b(?:max\\-secondary\\-entries|max\\-object\\-size|total\\-max\\-size|process\\-vary|max\\-age|cache)(?!-)\\b"
        }
      ]
    },
    "schema-directives": {
      "patterns": [
        {
          "name": "keyword.other.directive.haproxy",
          "match": "\\b(?:tune\\.quic\\.frontend\\.conn\\-tx\\-buffers\\.limit|h2\\-workaround\\-bogus\\-websocket\\-clients|harden\\.reject\\-privileged\\-ports\\.quic|tune\\.quic\\.frontend\\.max\\-idle\\-timeout|tune\\.quic\\.frontend\\.max\\-streams\\-bidi|harden\\.reject\\-privileged\\-ports\\.tcp|h1\\-accept\\-payload\\-with\\-any\\-method|tune\\.ssl\\.capture\\-cipherlist\\-size|ssl\\-default\\-server\\-ciphersuites|expose\\-experimental\\-directives|tune\\.h2\\.max\\-concurrent\\-streams|tune\\.peers\\.max\\-updates\\-at\\-once|deviceatlas\\-properties\\-cookie|ssl\\-default\\-bind\\-ciphersuites|tune\\.ssl\\.capture\\-buffer\\-size|tune\\.ssl\\.force\\-private\\-cache|httpclient\\.resolvers\\.prefer|load\\-server\\-state\\-from\\-file|tune\\.h2\\.initial\\-window\\-size|tune\\.ssl\\.ssl\\-ctx\\-cache\\-size|ssl\\-default\\-server\\-ciphers|ssl\\-default\\-server\\-options|tune\\.h2\\.header\\-table\\-size|tune\\.listener\\.multi\\-queue|tune\\.quic\\.retry\\-threshold|tune\\.ssl\\.default\\-dh\\-param|tune\\.vars\\.global\\-max\\-size|tune\\.vars\\.reqres\\-max\\-size|ssl\\-default\\-bind\\-ciphers|ssl\\-default\\-bind\\-options|tune\\.lua\\.service\\-timeout|tune\\.lua\\.session\\-timeout|tune\\.vars\\.check\\-max\\-size|httpclient\\.resolvers\\.id|ssl\\-default\\-bind\\-curves|ssl\\-skip\\-self\\-issued\\-ca|tune\\.pattern\\.cache\\-size|tune\\.pool\\-high\\-fd\\-ratio|tune\\.quic\\.reorder\\-ratio|tune\\.ssl\\.hard\\-maxrecord|tune\\.vars\\.proc\\-max\\-size|tune\\.vars\\.sess\\-max\\-size|httpclient\\.ssl\\.ca\\-file|insecure\\-setuid\\-wanted|server\\-state\\-file\\-name|ssl\\-load\\-extra\\-del\\-ext|tune\\.fd\\.edge\\-triggered|tune\\.h2\\.max\\-frame\\-size|tune\\.pool\\-low\\-fd\\-ratio|tune\\.sched\\.low\\-latency|tune\\.vars\\.txn\\-max\\-size|accepted_payload_size|deviceatlas\\-json\\-file|deviceatlas\\-log\\-level|deviceatlas\\-separator|http\\-send\\-name\\-header|httpclient\\.ssl\\.verify|max\\-secondary\\-entries|max\\-session\\-srv\\-conns|tune\\.idle\\-pool\\.shared|tune\\.lua\\.forced\\-yield|tune\\.lua\\.task\\-timeout|insecure\\-fork\\-wanted|max\\-keep\\-alive\\-queue|pp2\\-never\\-send\\-local|ssl\\-load\\-extra\\-files|tune\\.buffers\\.reserve|tune\\.zlib\\.windowsize|h1\\-case\\-adjust\\-file|hash\\-balance\\-factor|http\\-after\\-response|lua\\-load\\-per\\-thread|mworker\\-max\\-reloads|tune\\.http\\.cookielen|tune\\.http\\.logurilen|tune\\.runqueue\\-depth|dynamic\\-cookie\\-key|issuers\\-chain\\-path|no\\-memory\\-trimming|tune\\.buffers\\.limit|tune\\.comp\\.maxlevel|tune\\.maxpollevents|tune\\.rcvbuf\\.client|tune\\.rcvbuf\\.server|tune\\.sndbuf\\.client|tune\\.sndbuf\\.server|tune\\.ssl\\.cachesize|tune\\.ssl\\.maxrecord|tune\\.zlib\\.memlevel|close\\-spread\\-time|log\\-send\\-hostname|max\\-spread\\-checks|parse\\-resolv\\-conf|server\\-state\\-base|server\\-state\\-file|ssl\\-dh\\-param\\-file|ssl\\-provider\\-path|ssl\\-server\\-verify|tune\\.ssl\\.lifetime|error\\-log\\-format|lua\\-prepend\\-path|numa\\-cpu\\-mapping|profiling\\.memory|tune\\.http\\.maxhdr|tune\\.recv_enough|unique\\-id\\-format|unique\\-id\\-header|default_backend|hard\\-stop\\-after|max\\-object\\-size|maxcompcpuusage|profiling\\.tasks|resolve_retries|server\\-template|tune\\.fail\\-alloc|tune\\.lua\\.maxmem|tune\\.maxrewrite|tune\\.ssl\\.keylog|clitcpka\\-intvl|cluster\\-secret|default\\-server|h1\\-case\\-adjust|ignore\\-persist|srvtcpka\\-intvl|ssl\\-mode\\-async|total\\-max\\-size|tune\\.idletimer|tune\\.maxaccept|clitcpka\\-idle|fd\\-hard\\-limit|force\\-persist|http\\-response|log\\-format\\-sd|master\\-worker|no\\-verifyhost|nogetaddrinfo|spread\\-checks|srvtcpka\\-idle|ssl\\-propquery|strict\\-limits|thread\\-groups|tune\\.pipesize|backing\\-file|bind\\-process|busy\\-polling|clitcpka\\-cnt|default\\-bind|default\\-path|http\\-request|process\\-vary|quic\\-initial|set\\-dumpable|srvtcpka\\-cnt|ssl\\-provider|tcp\\-response|thread\\-group|tune\\.bufsize|use\\-fcgi\\-app|zero\\-warning|compression|description|errorloc302|errorloc303|http\\-errors|log\\-forward|maxcomprate|maxconnrate|maxsessrate|monitor\\-uri|noreuseport|pass\\-header|tcp\\-request|use_backend|clitimeout|contimeout|dgram\\-bind|errorfiles|http\\-check|http\\-error|http\\-reuse|log\\-format|log\\-stderr|maxsslconn|maxsslrate|maxzlibmem|nameserver|rate\\-limit|srvtimeout|ssl\\-engine|use\\-server|errorfile|hash\\-type|localpeer|noevports|path\\-info|presetenv|set\\-param|unix\\-bind|crt\\-base|dispatch|errorloc|fcgi\\-app|fullconn|lua\\-load|maxpipes|nbthread|nokqueue|nosplice|resetenv|retry\\-on|ulimit\\-n|unsetenv|userlist|balance|ca\\-base|command|cpu\\-map|declare|docroot|log\\-tag|mailers|max\\-age|noepoll|pidfile|program|retries|timeout|chroot|daemon|filter|format|mailer|maxlen|nopoll|option|server|setenv|cache|grace|index|peers|quiet|stats|table|bind|hold|mode|node|peer|ring|size|acl|log)(?!-)\\b"
        }
      ]
    },
    "directives-with-values": {
      "patterns": [
        {
